using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerInput : MonoBehaviour
{
    public PlayerInputActions InputActions { get; private set; }

    public PlayerInputActions.PlayerActions PlayerActions { get; private set; }

    /// <summary>
    /// Awake is called when the script instance is being loaded.
    /// </summary>
    void Awake()
    {
        InputActions = new();
        PlayerActions = InputActions.Player;
    }


    /// <summary>
    /// This function is called when the object becomes enabled and active.
    /// </summary>
    void OnEnable()
    {
        InputActions.Enable();
    }


    /// <summary>
    /// This function is called when the behaviour becomes disabled or inactive.
    /// </summary>
    void OnDisable()
    {
        InputActions.Disable();
    }


    public void DisablActionFor(InputAction action, float seconds)
    {

        StartCoroutine(DisablAction());
        IEnumerator DisablAction()
        {
            action.Disable();
            yield return new WaitForSeconds(seconds);
            action.Enable();
        }
    }


    public void DisablAction(InputAction action)
    {
        action.Disable();
    }


    public void EnableAction(InputAction action)
    {
        action.Enable();
    }
}
